const data = {
  movies: [
    {
      title: "Thor: Love and Thunder",
      slug: "Thor-love-and-thunder",
      release_date: "6-Jul-2022",
      genre: "Action/Sci-fi",
      running_time: "1h 59m",
      release_state: "now_showing",
      image: "/images/Thor_Love_and_Thunder.png",
    },
    {
      title: "Beast",
      slug: "Beast",
      release_date: "19-Aug-2022",
      genre: "Thriller/Adventure",
      running_time: "1h 33m",
      release_state: "now_showing",
      image: "/images/Beast.jpg",
    },
    {
      title: "Black Adam",
      slug: "Black-adam",
      release_date: "21-Oct-2022",
      genre: "Action/Fantasy",
      running_time: "2h 15m",
      release_state: "coming_soon",
      image: "/images/Black_Adam.jpg",
    },
    {
      title: "Blacklight",
      slug: "Blacklight",
      release_date: "10-Feb-2022",
      genre: "Action/Thriller",
      running_time: "1h 48m",
      release_state: "now_showing",
      image: "/images/Blacklight.jpg",
    },
    {
      title: "Bullet Train",
      slug: "Bullet-train",
      release_date: "5-Aug-2022",
      genre: "Action/Thriller",
      running_time: "2h 6m",
      release_state: "now_showing",
      image: "/images/Bullet_Train.png",
    },
    {
      title: "Daylight",
      slug: "Daylight",
      release_date: "12-Aug-2022",
      genre: "Comedy/Fantasy",
      running_time: "1h 54m",
      release_state: "now_showing",
      image: "/images/Daylight.jpg",
    },
    {
      title: "Elvis",
      slug: "Elvis",
      release_date: "19-Oct-2022",
      genre: "Musical/Drama",
      running_time: "2h 39m",
      release_state: "coming_soon",
      image: "/images/Elvis.jpg",
    },
    {
      title: "Jurassic World Dominion",
      slug: "Jurassic-world-dominion",
      release_date: "10-Jun-2022",
      genre: "Action/Sci-fi",
      running_time: "2h 27m",
      release_state: "now_showing",
      image: "/images/Jurassic_World.png",
    },
    {
      title: "Luck",
      slug: "Luck",
      release_date: "5-Aug-2022",
      genre: "Comedy/Family",
      running_time: "1h 37m",
      release_state: "now_showing",
      image: "/images/Luck.png",
    },
    {
      title: "The Unbearable Weight of Massive Talent",
      slug: "The-Unbearable-Weight-of-Massive-Talent",
      release_date: "12-Apr-2022",
      genre: "Action/Comedy",
      running_time: "1h 45m",
      release_state: "now_showing",
      image: "/images/Massive_Talent.jpg",
    },
    {
      title: "Me Time",
      slug: "Me-time",
      release_date: "26-Oct-2022",
      genre: "Action/Comedy",
      running_time: "1h 41m",
      release_state: "coming_soon",
      image: "/images/Me_Time.png",
    },
    {
      title: "Minions: The Rise of Gru",
      slug: "Minions-The-Rise-of-Gru",
      release_date: "1-Oct-2022",
      genre: "Comedy/Adventure",
      running_time: "1h 30m",
      release_state: "coming_soon",
      image: "/images/Minions.png",
    },
    {
      title: "Nope",
      slug: "Nope",
      release_date: "22-Jul-2022",
      genre: "Horror/Sci-fi",
      running_time: "2h 15m",
      release_state: "now_showing",
      image: "/images/Nope.jpg",
    },
    {
      title: "Samaritan",
      slug: "Samaritan",
      release_date: "15-Oct-2022",
      genre: "Action/Fantasy",
      running_time: "1h 41m",
      release_state: "coming_soon",
      image: "/images/Samaritan.jpg",
    },
    {
      title: "Top Gun: Maverick",
      slug: "Top-Gun-Maverick",
      release_date: "23-Jun-2022",
      genre: "Action/Adventure",
      running_time: "2h 11m",
      release_state: "now_showing",
      image: "/images/Top_Gun_Maverick.jpg",
    },
  ],
};

export default data;
